### ISSUE TITLE
Non Valide

### ISSUE THREAD

**Issue by exsit** [MicrosoftDocs/windowsserverdocs.fr-fr#2]
Le disque dynamique apparait comme "non valide", il me semble que cela n'est pas décrit dans cette page.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d347f950-4249-15da-2b61-6cc51f5fbb28
* Version Independent ID: cce0393d-b49e-0530-c4c1-679763ab61bf
* Content: [Résolution des problèmes de la Gestion des disques](https://docs.microsoft.com/fr-fr/windows-server/storage/disk-management/troubleshooting-disk-management#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md](https://github.com/MicrosoftDocs/windowsserverdocs.fr-fr/blob/live/WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @exsit
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @exsit,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/windowsserverdocs/issues/3918.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
