### ISSUE TITLE
Error in the french translation

### ISSUE THREAD

**Issue by FJduFou** [MicrosoftDocs/windowsserverdocs.fr-fr#5]
"S’il est utilisé avec les paramètres /f, /r, /xou /b , il corrige les erreurs sur le volume."
-&gt; "S’il est utilisé avec les paramètres /f, /r, /x ou /b , il corrige les erreurs sur le volume."
=&gt; Just add space: before=(/xou), after=(/x ou)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e39de773-2483-f94c-45aa-32b6af9775a1
* Version Independent ID: 03ba7ec3-9c97-5572-3e41-9ffd0ce916f0
* Content: [CHKDSK](https://docs.microsoft.com/fr-fr/windows-server/administration/windows-commands/chkdsk#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs.fr-fr/blob/live/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by FJduFou** [comment]
#6

**Comment by srvbpigh** [comment]
Hello, @FJduFou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @FJduFou 

Merci pour votre contribution. 

Les contributions relatives aux problèmes de traduction dans le contenu traduit automatiquement ne sont actuellement pas acceptées. 

Nous apprécions vos contributions et suggestions au contenu issu de la traduction humaine, qui sont utilisées pour effectuer l’apprentissage des moteurs de traduction automatique. Vos contributions amélioreront ainsi la qualité des traductions humaine et machine. 

Pour distinguer les rubriques traduites manuellement de celles traduites automatiquement, référez-vous à la valeur de métadonnées ms.translationtype qui figure dans l’en-tête de chaque fichier de contenu : "HT" fait référence à la traduction humaine et "MT" à la traduction machine. 

Un grand merci pour votre aide. 

L’équipe Microsoft DOCS Global Experience

**Comment by FJduFou** [comment]
@CeciAc merci mais comment puis-je alors faire en sorte que cette erreur soit corriger ?
