### ISSUE TITLE
Probleme pour déplacer les données utilisateurs

### ISSUE THREAD

**Issue by Rodolphe33** [MicrosoftDocs/windowsserverdocs.fr-fr#8]
Bonjour, je recherche de l'information pour débloquer mon petit probleme.

Pour faire simple, je souhaite déplacer mes données utilisateurs.

J'ai utilisé la commande:  
robocopy "C:\Users" "D:\Users" /E /COPYALL /XJ  

A un moment, le systeme n'arrive pas à copier un fichier, il réessai au bout de 30s.
J'ai laissé tourner la commande pendant plus de 8h, mais reste bloqué sur le fichier qui ne se copie pas.

Y-a t'il une possibilité de faire abstraction de ces fichiers qui ne se copie pas?

Merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/fr-fr/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs.fr-fr/blob/live/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Bonjour @Rodolphe33,

Nous développons notre pipeline de processus interne et d’ingénierie. Malheureusement, cela se traduit par des retards dans le traitement de vos commentaires.

Nous apprécions beaucoup votre contribution à nos articles et comptons sur votre aide et votre compréhension.

**Comment by Rodolphe33** [comment]
J
